version: "3.1"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "8082:3306"

  elasticsearch:
    image: elasticsearch:5.4-alpine

  web:
    restart: always
    build: configuration/nginx
    depends_on:
      - php-fpm
    ports:
      - "8888:80"
    volumes:
      - ./configuration/nginx/default.conf:/etc/nginx/sites-available/default.conf
      - ./configuration/nginx/default.conf:/etc/nginx/sites-enabled/default.conf
      - .:/var/www/html
    networks:
      - webnet

  php-fpm:
    image: php:7.1.11-fpm-alpine
    depends_on:
      - composer
    expose:
      - 9000
    volumes:
      - ./backend:/var/www/backend
      - ./configuration/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
    # command: >
      # php init --env=Local --overwrite=y
      # php yii migrate << "yes"
    networks:
      - webnet

  composer:
    image: composer/composer:php7
    command: install
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend

  nodejs:
    image: node:8
    volumes:
      - ./frontend:/frontend
      - ./api:/api

networks:
  webnet:
