- name: generate the server locale
  locale_gen: name={{ locale }} state=present

- name: set locale
  lineinfile: dest=/etc/default/locale regexp='^LANG' line='LANG={{ locale }}'

- name: reload locale
  raw: . /etc/default/locale

- name: add git apt-repository
  apt_repository: repo='ppa:git-core/ppa' state=present update_cache=yes

- name: install apt packages
  apt: name={{item}}
  with_items:
    - git
    - unzip
