- name: add php ppa
  apt_repository: repo='ppa:ondrej/php' state=present

- name: update apt cache
  apt: update_cache=yes

- name: install php
  apt: name=php{{ php.version }} state=present

- name: install php requirements
  apt: name=php{{ php.version }}-{{ item }} state=present
  with_items: 
    - xml
    - curl
    - mbstring
    - mysql
    - gd
    - zip

- name: install php-xdebug & mod-php
  apt: name={{ item }} state=present
  with_items:
    - php-xdebug
    # - libapache2-mod-php

- name: update xdebug config
  copy: src=xdebug.ini dest=/etc/php/{{ php.version }}/{{ item }}/conf.d/20-xdebug.ini
  with_items:
    - cli
    - apache2
  ignore_errors: yes
